test1: test1.cpp
	rm -f a.out
	g++ -g -std=c++17 test1.cpp

gen: gen2.cpp
	rm -f gen
	g++ -g -std=c++17 gen2.cpp -o gen

all: KnightScape.cpp
	g++ -g -std=c++17 KnightScape.cpp -o KnightScape
clean:
	rm -f KnightScape *~
	clear
